# Generated by Django 3.1.6 on 2021-03-07 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210301_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='date_created',
            new_name='dateCreated',
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(help_text='This is not required, but this could help your product gain the spotlight it deserves! Examples of categories include Fashion, Toys, Electronics, Home, etc.', on_delete=django.db.models.deletion.CASCADE, related_name='similar_items', to='auctions.category'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(help_text='A longer description displayed for the listing', max_length=1024),
        ),
        migrations.AlterField(
            model_name='listing',
            name='imageURL',
            field=models.CharField(blank=True, help_text='What is the image displayed for the listing', max_length=2048),
        ),
        migrations.AlterField(
            model_name='listing',
            name='item',
            field=models.CharField(help_text='The title displayed for the listing', max_length=64),
        ),
        migrations.AlterField(
            model_name='listing',
            name='startBid',
            field=models.IntegerField(default=0, help_text='What is the starting price displayed for the listing'),
        ),
    ]
