# Generated by Django 3.1.6 on 2021-03-08 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210307_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='acution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.listing'),
        ),
    ]
