# Generated by Django 3.1.6 on 2021-06-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210321_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='category',
            new_name='categ',
        ),
        migrations.AddField(
            model_name='category',
            name='supCategory',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
