# Generated by Django 3.1.6 on 2021-06-01 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210601_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='categ',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='supCategory',
        ),
    ]
